# Generated by Django 3.1.6 on 2021-02-19 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='missingPersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='null', max_length=50)),
                ('lastname', models.CharField(default='null', max_length=50)),
                ('age', models.IntegerField(default='null')),
                ('gender', models.TextField(default='null')),
                ('color', models.CharField(default='null', max_length=50)),
                ('height', models.CharField(default='null', max_length=50)),
                ('datetime', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('placemissing', models.CharField(default='null', max_length=50)),
                ('police_st', models.TextField(default='null')),
                ('desc', models.TextField(default='null')),
                ('image', models.ImageField(default='default.jpg', upload_to='media/missing_person_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
