# Generated by Django 3.1.6 on 2021-02-18 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='missingPersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='null', max_length=50)),
                ('lastname', models.CharField(default='null', max_length=50)),
                ('age', models.IntegerField(default='null')),
                ('gender', models.TextField(default='null')),
                ('color', models.CharField(default='null', max_length=50)),
                ('height', models.CharField(default='null', max_length=50)),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('placemissing', models.CharField(default='null', max_length=50)),
                ('police_st', models.TextField(default='null')),
                ('desc', models.TextField(default='null')),
            ],
        ),
    ]
