# Generated by Django 3.1.6 on 2021-02-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingPerson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersoninfo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='missing_person_pics'),
        ),
    ]
