# Generated by Django 3.1.6 on 2021-02-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingPerson', '0002_missingpersoninfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpersoninfo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/missing_person_pics'),
        ),
    ]
