# Generated by Django 3.1.6 on 2021-02-21 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('missingPerson', '0002_auto_20210220_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersoninfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 21, 11, 24, 55, 216202, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
