# Generated by Django 3.1.6 on 2021-02-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missingPerson', '0003_auto_20210219_1232'),
        ('missingPerson', '0003_auto_20210219_1147'),
    ]

    operations = [
    ]
