# Generated by Django 3.1.6 on 2021-02-19 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missingPerson', '0004_merge_20210219_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersoninfo',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
