# Generated by Django 3.1.6 on 2021-02-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingPerson', '0005_auto_20210223_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersoninfo',
            name='admin_message',
            field=models.CharField(default='Your complaint is under review.We will get back to you soon.', max_length=250),
        ),
    ]
