# Generated by Django 3.1.6 on 2021-02-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_manual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
