# Generated by Django 3.1.6 on 2021-02-16 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propOwnerFullName', models.CharField(max_length=50)),
                ('propOwnerContact', models.CharField(max_length=30)),
                ('propOwnerEmail', models.EmailField(max_length=254)),
                ('propOwnerFlatno', models.CharField(max_length=50)),
                ('propOwnerAddress', models.CharField(max_length=50)),
                ('propOwnerCity', models.CharField(max_length=50)),
                ('propOwnerState', models.CharField(max_length=50)),
                ('propOwnerCountry', models.CharField(max_length=50)),
                ('tenantFullName', models.CharField(max_length=50)),
                ('tenantContact', models.CharField(max_length=30)),
                ('tenantEmail', models.EmailField(max_length=254)),
                ('tenantFlatno', models.CharField(max_length=50)),
                ('tenantAddress', models.CharField(max_length=50)),
                ('tenantCity', models.CharField(max_length=50)),
                ('tenantState', models.CharField(max_length=50)),
                ('tenantCountry', models.CharField(max_length=50)),
                ('tenantDOB', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tenantReason', models.TextField()),
                ('tenantOrganisation', models.CharField(max_length=50)),
                ('tenantDepartment', models.CharField(max_length=50)),
                ('tenantID', models.CharField(max_length=50)),
                ('tenantInstitute', models.CharField(max_length=50)),
                ('tenantBranch', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
