# Generated by Django 3.1.6 on 2021-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationinfo',
            name='desc',
            field=models.TextField(default='Not Applicable'),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantBranch',
            field=models.CharField(default='Not Applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantDepartment',
            field=models.CharField(default='Not Applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantID',
            field=models.CharField(default='Not Applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantInstitute',
            field=models.CharField(default='Not Applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantOrganisation',
            field=models.CharField(default='Not Applicable', max_length=50),
        ),
    ]
