# Generated by Django 3.1.6 on 2021-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_auto_20210216_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationinfo',
            name='propOwnerAddress',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='propOwnerCity',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='propOwnerContact',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='propOwnerCountry',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='propOwnerEmail',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='propOwnerFlatno',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='propOwnerFullName',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='propOwnerState',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantAddress',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantCity',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantContact',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantCountry',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantEmail',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantFlatno',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantFullName',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantReason',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='verificationinfo',
            name='tenantState',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
