# Generated by Django 3.1.6 on 2021-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_auto_20210220_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationinfo',
            name='admin_status',
            field=models.CharField(default='under scrutiny', max_length=30),
        ),
    ]
