# Generated by Django 3.1.6 on 2021-02-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0008_auto_20210223_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationinfo',
            name='ack_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
