# Generated by Django 3.1.6 on 2021-02-16 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stolenVehiclesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=50)),
                ('chassis_no', models.CharField(max_length=50)),
                ('engine_no', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
