# Generated by Django 3.1.6 on 2021-02-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolenVehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolenvehiclesinfo',
            name='desc',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='stolenvehiclesinfo',
            name='police_station',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='chassis_no',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='contact',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='engine_no',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='fullName',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='model_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='reg_no',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
