# Generated by Django 3.1.6 on 2021-02-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolenVehicles', '0002_auto_20210216_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='desc',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='police_station',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
