# Generated by Django 3.1.6 on 2021-02-21 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stolenVehicles', '0005_stolenvehiclesinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolenvehiclesinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
