# Generated by Django 3.1.6 on 2021-02-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolenVehicles', '0007_stolenvehiclesinfo_ack_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolenvehiclesinfo',
            name='admin_message',
            field=models.CharField(default='Your complaint is under review.We will get back to you soon.', max_length=250),
        ),
    ]
