# Generated by Django 3.1.6 on 2021-02-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolenVehicles', '0008_stolenvehiclesinfo_admin_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='chassis_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='engine_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='fullName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='model_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='police_station',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stolenvehiclesinfo',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
