import os
from django.contrib.gis.utils import LayerMapping
from .models import Maha0

maha0_mapping = {
    'id_0': 'ID_0',
    'iso': 'ISO',
    'name_0': 'NAME_0',
    'objectid_1': 'OBJECTID_1',
    'iso3': 'ISO3',
    'name_engli': 'NAME_ENGLI',
    'name_iso': 'NAME_ISO',
    'name_fao': 'NAME_FAO',
    'name_local': 'NAME_LOCAL',
    'name_obsol': 'NAME_OBSOL',
    'name_varia': 'NAME_VARIA',
    'name_nonla': 'NAME_NONLA',
    'name_frenc': 'NAME_FRENC',
    'name_spani': 'NAME_SPANI',
    'name_russi': 'NAME_RUSSI',
    'name_arabi': 'NAME_ARABI',
    'name_chine': 'NAME_CHINE',
    'waspartof': 'WASPARTOF',
    'contains': 'CONTAINS',
    'sovereign': 'SOVEREIGN',
    'iso2': 'ISO2',
    'www': 'WWW',
    'fips': 'FIPS',
    'ison': 'ISON',
    'validfr': 'VALIDFR',
    'validto': 'VALIDTO',
    'pop2000': 'POP2000',
    'sqkm': 'SQKM',
    'popsqkm': 'POPSQKM',
    'unregion1': 'UNREGION1',
    'unregion2': 'UNREGION2',
    'developing': 'DEVELOPING',
    'cis': 'CIS',
    'transition': 'Transition',
    'oecd': 'OECD',
    'wbregion': 'WBREGION',
    'wbincome': 'WBINCOME',
    'wbdebt': 'WBDEBT',
    'wbother': 'WBOTHER',
    'ceeac': 'CEEAC',
    'cemac': 'CEMAC',
    'ceplg': 'CEPLG',
    'comesa': 'COMESA',
    'eac': 'EAC',
    'ecowas': 'ECOWAS',
    'igad': 'IGAD',
    'ioc': 'IOC',
    'mru': 'MRU',
    'sacu': 'SACU',
    'uemoa': 'UEMOA',
    'uma': 'UMA',
    'palop': 'PALOP',
    'parta': 'PARTA',
    'cacm': 'CACM',
    'eurasec': 'EurAsEC',
    'agadir': 'Agadir',
    'saarc': 'SAARC',
    'asean': 'ASEAN',
    'nafta': 'NAFTA',
    'gcc': 'GCC',
    'csn': 'CSN',
    'caricom': 'CARICOM',
    'eu': 'EU',
    'can': 'CAN',
    'acp': 'ACP',
    'landlocked': 'Landlocked',
    'aosis': 'AOSIS',
    'sids': 'SIDS',
    'islands': 'Islands',
    'ldc': 'LDC',
    'geom': 'MULTIPOLYGON',
}

maha_shp = os.path.abspath(os.path.join(os.path.dirname(__file__), 'data/IND_adm0.shp'))

def run(verbose=True):
    lm = LayerMapping(Maha0, maha_shp, maha0_mapping, transform=False, encoding='iso-8859-1')
    lm.save(strict=True, verbose=verbose)
