# Generated by Django 3.1.6 on 2021-02-16 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='criminalsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='null', max_length=50)),
                ('lastname', models.CharField(default='null', max_length=50)),
                ('age', models.IntegerField(default='null')),
                ('gender', models.TextField(default='null')),
                ('address', models.TextField(default='null')),
                ('pincode', models.IntegerField(default='null')),
                ('prison_sentence', models.IntegerField(default='null')),
                ('crime', models.TextField(default='null')),
                ('current_status', models.TextField(default='null')),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('desc', models.TextField(default='null')),
            ],
        ),
    ]
