# Generated by Django 3.1.6 on 2021-02-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalsinfo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='criminal_pics'),
        ),
    ]
