# Generated by Django 3.1.6 on 2021-02-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0002_criminalsinfo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminalsinfo',
            old_name='fullName',
            new_name='firstname',
        ),
    ]
