# Generated by Django 3.1.6 on 2021-02-19 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0004_auto_20210219_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalsinfo',
            name='age',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='criminalsinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], default='null', max_length=5),
        ),
    ]
