# Generated by Django 3.1.6 on 2021-02-26 10:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0009_auto_20210226_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalsinfo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
