# Generated by Django 3.1.6 on 2021-02-23 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='null', max_length=50)),
                ('contact', models.CharField(default='null', max_length=30)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('flatno', models.CharField(default='null', max_length=50)),
                ('address', models.CharField(default='null', max_length=50)),
                ('city', models.CharField(default='null', max_length=50)),
                ('state', models.CharField(default='null', max_length=50)),
                ('country', models.CharField(default='null', max_length=50)),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('crime', models.CharField(choices=[('cyber', 'Cyber'), ('extortion', 'Extortion'), ('chain snatching', 'Chain Snatching'), ('dacotiy', 'Dacoity'), ('theft', 'Theft'), ('others', 'Others')], default='null', max_length=50)),
                ('desc', models.CharField(default='null', max_length=250)),
                ('admin_status', models.CharField(choices=[('under scrutiny', 'Under Scrutiny'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under scrutiny', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ack_no', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
