# Generated by Django 3.1.6 on 2021-02-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaintsinfo_admin_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsinfo',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='crime',
            field=models.CharField(default='others', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='flatno',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='fullName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
