# Generated by Django 3.1.6 on 2021-02-11 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaintsinfo_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsinfo',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
