# Generated by Django 3.1.6 on 2021-02-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20210224_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
