# Generated by Django 3.1.6 on 2021-02-13 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20210211_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsinfo',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
