# Generated by Django 3.1.6 on 2021-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20210213_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsinfo',
            name='address',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='city',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='contact',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='country',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='crime',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='desc',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='flatno',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='fullName',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintsinfo',
            name='state',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
