# Generated by Django 3.1.6 on 2021-02-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_auto_20210220_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsinfo',
            name='admin_status',
            field=models.CharField(choices=[('under scrutiny', 'Under Scrutiny'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='null', max_length=50),
        ),
    ]
