# Generated by Django 3.1.6 on 2021-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaintsinfo_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsinfo',
            name='admin_status',
            field=models.CharField(choices=[('under scrutiny', 'Under Scrutiny'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under scrutiny', max_length=50),
        ),
    ]
