# Generated by Django 3.1.6 on 2021-02-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20210224_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidences',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=72, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidences',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=19, max_digits=15),
            preserve_default=False,
        ),
    ]
